# SQL
CREATE DATABASE employee;
USE employee;
create table departments (department_id int primary key, department_name varchar(100) not null unique);
create table location (location_id int primary key auto_increment, location varchar(30) not null unique);
create table employees (employee_id int primary key, employee_name varchar (50) not null);
alter table  employees add gender enum("m","f");
show tables;
describe employees;
alter table employees add age int check(age>=18);
alter table employees add hire_date date default(current_date);
alter table employees add designation varchar(100);
alter table employees add department_id int;
alter table employees add location_id int;
alter table employees add salary decimal(10,2);
alter table employees add foreign key (department_id) references departments(department_id);
alter table employees add foreign key (location_id) references location(location_id);
alter table employees add email varchar(100);
alter table employees modify designation varchar(150);
alter table employees drop column age;
alter table employees rename column hire_date to date_of_joining;
rename table departments to departments_info;
rename table location to locations;
truncate table employees;
drop table employees;
drop  database employee;
drop database if exists employee;
create database employee;
use employee;
create table departments(department_id int primary key, departmant_name varchar(100) not null unique);
create table location( location_id int primary  key auto_increment, location varchar(30) not null unique);
create table employees(employee_id int primary key,  employee_name varchar(50) not null);

use employee;
alter table employees add gender enum("m","f");
alter table employees add hire_date date default(current_date);
alter table employees add age int check(age>=18);
alter table employees add designation varchar(100);
alter table employees add department_id int;
alter table employees add location_id int;
alter table employees add salary decimal(10,2);
alter table employees add foreign key(department_id)references departments(department_id);
alter table employees add foreign key(location_id)references location(location_id);
alter table employees modify gender enum('M','F');

